/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component RubyExample
 * @description  - Composed Example
 */

import { Ruby } from './ruby';

/**
 * RubyExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, Main, MarkedText, Paragraph, Section
 * - Can contain: RubyParenthesis, RubyText
 */
export class RubyExample {
  static create(): HTMLElement {
    const element = new Ruby();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
