/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component TheadExample
 * @description  - Composed Example
 */

import { Thead } from './thead';

/**
 * TheadExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Table
 * - Can contain: TableRow
 */
export class TheadExample {
  static create(): HTMLElement {
    const element = new Thead();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
