/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Ul - Composed Template
 * @description The ul element represents an unordered list of items, namely a collection of items that do not have a numerical ordering, and their order in the list is meaningless.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, ListItem, Main, Paragraph, Section, Slot, Template
 * - Can contain: ListItem
 */

import React from 'react';
import { Ul } from '../block/ul';
import { Li } from '../block/li';

/**
 * Example usage of Ul with valid content model
 */
export const UlExample: React.FC = () => {
  return (
    <Ul className="example">
      <Li>Item 1</Li>
      <Li>Item 2</Li>
    </Ul>
  );
};

UlExample.displayName = 'UlExample';
