/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Ol - Composed Example
 * @description The ol element represents an ordered list of items. The order of the list is meaningful.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, ListItem, Main, Paragraph, Section, Slot, Template
 * - Can contain: ListItem
 */

import * as LiStories from './../../block/li/li.stories.js';

export default {
  title: "HTML5/Content Model/Ol - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The ol element represents an ordered list of items. The order of the list is meaningful.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Ol with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('ol');
    parent.className = 'example';

    const child0 = LiStories.default.render(LiStories.Default.args);
    parent.appendChild(child0);
    const child1 = LiStories.default.render(LiStories.Default.args);
    parent.appendChild(child1);

    return parent;
  },
};
