/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component FormExample
 * @description  - Composed Example
 */

import { Form } from './form';

/**
 * FormExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Article, Body, DefinitionDescription, Details, Dialog, Division, Header, Main, MarkedText, Menu, Paragraph, Section, Slot, Template
 * - Can contain: Button, Canvas, DataList, Details, Dialog, Fieldset, Input, Label, Legend, Meter, NoScript, Output, Progress, Script, Select, Slot, Summary, Template, Textarea
 */
export class FormExample {
  static create(): HTMLElement {
    const element = new Form();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
