/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Datalist - Composed Template
 * @description The datalist element contains a set of option elements that represent the permissible or recommended options available to users.
 *
 * CONTENT MODEL:
 * - Can be a child of: Body, Fieldset, Form
 * - Can contain: Option
 */

import React from 'react';
import { Datalist } from '../block/datalist';
import { Option } from '../block/option';

/**
 * Example usage of Datalist with valid content model
 */
export const DatalistExample: React.FC = () => {
  return (
    <Datalist className="example">
      <Option value="0">Option 1</Option>
      <Option value="1">Option 2</Option>
    </Datalist>
  );
};

DatalistExample.displayName = 'DatalistExample';
