/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component DdExample
 * @description  - Composed Example
 */

import { Dd } from './dd';

/**
 * DdExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: DefinitionList, Aside, DefinitionDescription, Division, Footer, Header, Main, Section
 * - Can contain: Anchor, Abbreviation, Area, Audio, Bold, BidirectionalIsolation, BidirectionalOverride, BreakElement, Citation, Code, Data, DefinitionDescription, DeletedText, Definition, Division, DefinitionList, DefinitionTerm, Emphasis, Embed, Figure, Form, Italic, InlineFrame, Image, InsertedText, Button, Input, Select, Textarea, Details, Summary, KeyboardInput, ListItem, Map, MarkedText, ObjectElement, OrderedList, Paragraph, Parameter, Picture, PreformattedText, Quotation, RubyParenthesis, RubyText, Ruby, Strikethrough, SampleOutput, Small, Source, Span, Strong, Subscript, Superscript, Table, Time, Track, Underline, UnorderedList, Variable, Video, WordBreakOpportunity
 */
export class DdExample {
  static create(): HTMLElement {
    const element = new Dd();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
