/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Html
 * @description 
 */

export interface HtmlProps {
  /**
   * Child content or elements
   */
  children?: string | HTMLElement | (string | HTMLElement)[];
  /**
   * Represents the text direction of the element
   */
  dir?: 'ltr' | 'rtl' | 'auto' | null | undefined;
  /**
   * Specifies the primary language for the element's content
   */
  lang?: string | null | undefined;
  /**
   * Specifies the address of the document's cache manifest.
   */
  manifest?: string | null | undefined;
}

/**
 * Html - 
 */
export class Html {
  private element: HTMLElement;

  constructor(props: HtmlProps = {}) {
    this.element = document.createElement('html');
    this.applyProps(props);
  }

  private applyProps(props: HtmlProps): void {
    if (props.children !== undefined) {
      this.setChildren(props.children);
    }
    if (props.dir !== undefined) {
      this.setDir(props.dir);
    }
    if (props.lang !== undefined) {
      this.element.setAttribute('lang', String(props.lang));
    }
    if (props.manifest !== undefined) {
      this.element.setAttribute('manifest', String(props.manifest));
    }
  }

  setDir(value: 'ltr' | 'rtl' | 'auto' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('dir');
    } else {
      this.element.setAttribute('dir', String(value));
    }
    return this;
  }

  setLang(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('lang');
    } else {
      this.element.setAttribute('lang', String(value));
    }
    return this;
  }

  setManifest(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('manifest');
    } else {
      this.element.setAttribute('manifest', String(value));
    }
    return this;
  }

  setChildren(children: string | HTMLElement | (string | HTMLElement)[]): this {
    // Clear existing children
    while (this.element.firstChild) {
      this.element.removeChild(this.element.firstChild);
    }
    
    if (typeof children === 'string') {
      this.element.textContent = children;
    } else if (Array.isArray(children)) {
      children.forEach(child => {
        if (typeof child === 'string') {
          this.element.appendChild(document.createTextNode(child));
        } else {
          this.element.appendChild(child);
        }
      });
    } else {
      this.element.appendChild(children);
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
