/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Input
 * @description The input element represents a typed data field, usually with a form control to allow user input.
 */

import React from 'react';

export interface InputProps {
  /** CSS class names */
  className?: string;
  accept?: string;
  accesskey?: string;
  alt?: string;
  ariaAtomic?: 'false' | 'true';
  ariaAutocomplete?: 'none' | 'inline' | 'list' | 'both';
  ariaChecked?: 'false' | 'true' | 'mixed' | 'undefined';
  ariaControls?: string;
  ariaCurrent?: 'false' | 'page' | 'step' | 'location' | 'date' | 'time' | 'true';
  ariaDescribedby?: string;
  ariaDetails?: string;
  ariaDisabled?: 'false' | 'true';
  ariaExpanded?: 'false' | 'true' | 'undefined';
  ariaHaspopup?: 'false' | 'true' | 'menu' | 'listbox' | 'tree' | 'grid' | 'dialog';
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  ariaKeyshortcuts?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaLive?: 'off' | 'polite' | 'assertive';
  ariaPlaceholder?: string;
  ariaPressed?: 'false' | 'true' | 'mixed' | 'undefined';
  ariaReadonly?: 'false' | 'true';
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  ariaRequired?: 'false' | 'true';
  ariaRoledescription?: string;
  ariaValuemax?: number;
  ariaValuemin?: number;
  ariaValuenow?: number;
  ariaValuetext?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autocomplete?: 'off' | 'on';
  autocorrect?: 'off' | 'on';
  autofocus?: boolean;
  checked?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  dirname?: string;
  disabled?: boolean;
  draggable?: boolean;
  form?: string;
  formaction?: string;
  formenctype?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
  formmethod?: 'get' | 'post' | 'dialog';
  formnovalidate?: boolean;
  formtarget?: '_self' | '_blank' | '_parent' | '_top';
  height?: string;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  list?: string;
  max?: number;
  maxlength?: number;
  min?: string;
  minlength?: number;
  multiple?: boolean;
  name?: string;
  pattern?: string;
  placeholder?: string;
  popovertarget?: string;
  popovertargetaction?: 'show' | 'hide' | 'toggle';
  readonly?: boolean;
  required?: boolean;
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  size?: number;
  spellcheck?: 'true' | 'false';
  src?: string;
  step?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
  type?: 'button' | 'checkbox' | 'color' | 'date' | 'datetime-local' | 'email' | 'file' | 'hidden' | 'image' | 'month' | 'number' | 'password' | 'radio' | 'range' | 'reset' | 'search' | 'submit' | 'tel' | 'text' | 'time' | 'url' | 'week';
  value?: string;
  width?: string;
}

/**
 * Input - The input element represents a typed data field, usually with a form control to allow user input.
 */
export const Input: React.FC<InputProps> = (props: InputProps) => {
  const {
    className,
    accept,
    accesskey,
    alt,
    ariaAtomic,
    ariaAutocomplete,
    ariaChecked,
    ariaControls,
    ariaCurrent,
    ariaDescribedby,
    ariaDetails,
    ariaDisabled,
    ariaExpanded,
    ariaHaspopup,
    ariaInvalid,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLabelledby,
    ariaLive,
    ariaPlaceholder,
    ariaPressed,
    ariaReadonly,
    ariaRelevant,
    ariaRequired,
    ariaRoledescription,
    ariaValuemax,
    ariaValuemin,
    ariaValuenow,
    ariaValuetext,
    autocapitalize,
    autocomplete,
    autocorrect,
    autofocus,
    checked,
    contenteditable,
    dataSet,
    dir,
    dirname,
    disabled,
    draggable,
    form,
    formaction,
    formenctype,
    formmethod,
    formnovalidate,
    formtarget,
    height,
    hidden,
    id,
    inputmode,
    lang,
    list,
    max,
    maxlength,
    min,
    minlength,
    multiple,
    name,
    pattern,
    placeholder,
    popovertarget,
    popovertargetaction,
    readonly,
    required,
    role,
    size,
    spellcheck,
    src,
    step,
    style,
    tabindex,
    title,
    translate,
    type,
    value,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'autofocus' || key === 'checked' || key === 'disabled' || key === 'draggable' || key === 'formnovalidate' || key === 'hidden' || key === 'multiple' || key === 'readonly' || key === 'required')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'input',
    elementProps
  );
};

Input.displayName = 'Input';
