/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component FieldsetExample
 * @description  - Composed Example
 */

import { Fieldset } from './fieldset';

/**
 * FieldsetExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Body, Form, Paragraph
 * - Can contain: Button, DataList, Input, Label, Legend, Meter, Output, Progress, Select, Textarea
 */
export class FieldsetExample {
  static create(): HTMLElement {
    const element = new Fieldset();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
