/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Form - Composed Template
 * @description The form element represents a section of a document containing interactive controls for submitting information to a web server.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Body, DefinitionDescription, Details, Dialog, Division, Header, Main, MarkedText, Menu, Paragraph, Section, Slot, Template
 * - Can contain: Button, Canvas, DataList, Details, Dialog, Fieldset, Input, Label, Legend, Meter, NoScript, Output, Progress, Script, Select, Slot, Summary, Template, Textarea
 */

import React from 'react';
import { Form } from '../block/form';
import { Button } from '../inline/button';
import { Canvas } from '../block/canvas';
import { Datalist } from '../block/datalist';
import { Option } from '../block/option';
import { Details } from '../block/details';
import { Dialog } from '../block/dialog';
import { Fieldset } from '../block/fieldset';
import { Input } from '../inline/input';
import { Label } from '../inline/label';
import { Legend } from '../block/legend';
import { H1 } from '../block/h1';
import { H2 } from '../block/h2';
import { H3 } from '../block/h3';
import { H4 } from '../block/h4';
import { H5 } from '../block/h5';
import { H6 } from '../block/h6';
import { Meter } from '../inline/meter';
import { Noscript } from '../block/noscript';
import { Output } from '../inline/output';
import { Progress } from '../inline/progress';
import { Script } from '../void/script';
import { Select } from '../inline/select';
import { Optgroup } from '../block/optgroup';
import { Slot } from '../inline/slot';
import { Summary } from '../block/summary';
import { Template } from '../block/template';
import { Textarea } from '../inline/textarea';

/**
 * Example usage of Form with valid content model
 */
export const FormExample: React.FC = () => {
  return (
    <Form className="example">
      <Button type="submit">Submit</Button>
      <Button type="submit">Submit</Button>
      <Fieldset>
        <Button type="submit">Submit</Button>
        <Button type="submit">Submit</Button>
        <Input type="email" name="field1" />
        <Input type="number" name="field2" />
        <Label htmlFor="field2">Label 3:</Label>
        <Label htmlFor="field3">Label 4:</Label>
      </Fieldset>
      <Fieldset>
        <Button type="submit">Submit</Button>
        <Button type="submit">Submit</Button>
        <Input type="email" name="field1" />
        <Input type="number" name="field2" />
        <Label htmlFor="field2">Label 3:</Label>
        <Label htmlFor="field3">Label 4:</Label>
      </Fieldset>
      <Input type="number" name="field2" />
      <Input type="text" name="field3" />
    </Form>
  );
};

FormExample.displayName = 'FormExample';
