/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Img
 * @description The img element represents an image.
 */

import React from 'react';

export interface ImgProps {
  /** CSS class names */
  className?: string;
  alt?: string;
  ariaAtomic?: 'false' | 'true';
  ariaDetails?: string;
  ariaHidden?: 'false' | 'true';
  ariaKeyshortcuts?: string;
  ariaLabel?: string;
  ariaLive?: 'off' | 'polite' | 'assertive';
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  ariaRoledescription?: string;
  crossorigin?: 'anonymous' | 'use-credentials';
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  decoding?: 'async' | 'auto' | 'sync';
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  height?: string;
  hidden?: boolean;
  id?: string;
  ismap?: boolean;
  lang?: string;
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  sizes?: string;
  src?: string;
  srcset?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  usemap?: string;
  width?: string;
}

/**
 * Img - The img element represents an image.
 */
export const Img: React.FC<ImgProps> = (props: ImgProps) => {
  const {
    className,
    alt,
    ariaAtomic,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    crossorigin,
    dataSet,
    decoding,
    dir,
    draggable,
    height,
    hidden,
    id,
    ismap,
    lang,
    referrerpolicy,
    sizes,
    src,
    srcset,
    style,
    tabindex,
    title,
    usemap,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'draggable' || key === 'hidden' || key === 'ismap')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'img',
    elementProps
  );
};

Img.displayName = 'Img';
