/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Ul - Composed Example
 * @description The ul element represents an unordered list of items, namely a collection of items that do not have a numerical ordering, and their order in the list is meaningless.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, ListItem, Main, Paragraph, Section, Slot, Template
 * - Can contain: ListItem
 */

import * as LiStories from './../../block/li/li.stories.js';

export default {
  title: "HTML5/Content Model/Ul - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The ul element represents an unordered list of items, namely a collection of items that do not have a numerical ordering, and their order in the list is meaningless.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Ul with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('ul');
    parent.className = 'example';

    const child0 = LiStories.default.render(LiStories.Default.args);
    parent.appendChild(child0);
    const child1 = LiStories.default.render(LiStories.Default.args);
    parent.appendChild(child1);

    return parent;
  },
};
