/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Ruby - Composed Example
 * @description The ruby element represents a ruby annotation. Ruby annotations are short runs of text presented alongside base text, primarily used for East Asian typography to indicate pronunciation or to provide a short annotation.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, Main, MarkedText, Paragraph, Section
 * - Can contain: RubyParenthesis, RubyText
 */

import * as RpStories from './../../inline/rp/rp.stories.js';
import * as RtStories from './../../inline/rt/rt.stories.js';

export default {
  title: "HTML5/Content Model/Ruby - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The ruby element represents a ruby annotation. Ruby annotations are short runs of text presented alongside base text, primarily used for East Asian typography to indicate pronunciation or to provide a short annotation.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Ruby with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('ruby');
    parent.className = 'example';

    const child0 = RpStories.default.render(RpStories.Default.args);
    parent.appendChild(child0);
    const child1 = RpStories.default.render(RpStories.Default.args);
    parent.appendChild(child1);
    const child2 = RtStories.default.render(RtStories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
