/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component TableExample
 * @description  - Composed Example
 */

import { Table } from './table';

/**
 * TableExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, Main, MarkedText, Paragraph, Section, Slot, Template
 * - Can contain: Caption, ColumnGroup, TableBody, TableFoot, TableHead, TableRow
 */
export class TableExample {
  static create(): HTMLElement {
    const element = new Table();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
