/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component BlockquoteExample
 * @description  - Composed Example
 */

import { Blockquote } from './blockquote';

/**
 * BlockquoteExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Body, Paragraph
 * - Can contain: Article, Paragraph
 */
export class BlockquoteExample {
  static create(): HTMLElement {
    const element = new Blockquote();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
