/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component LegendExample
 * @description  - Composed Example
 */

import { Legend } from './legend';

/**
 * LegendExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Fieldset, Form
 * - Can contain: Heading1, Heading2, Heading3, Heading4, Heading5, Heading6
 */
export class LegendExample {
  static create(): HTMLElement {
    const element = new Legend();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
