/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Map - Composed Template
 * @description The map element, in conjunction with an img element and any area element descendants, defines an image map. The element represents a related collection of map areas.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, Main, MarkedText, Paragraph, Section
 * - Can contain: Area
 */

import React from 'react';
import { Map } from '../block/map';
import { Area } from '../void/area';

/**
 * Example usage of Map with valid content model
 */
export const MapExample: React.FC = () => {
  return (
    <Map className="example">
      <Area shape="rect" coords="0,0,100,100" href="#link0" alt="Area 0" />
      <Area shape="rect" coords="0,0,100,100" href="#link1" alt="Area 1" />
    </Map>
  );
};

MapExample.displayName = 'MapExample';
