/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Form - Composed Example
 * @description The form element represents a section of a document containing interactive controls for submitting information to a web server.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Body, DefinitionDescription, Details, Dialog, Division, Header, Main, MarkedText, Menu, Paragraph, Section, Slot, Template
 * - Can contain: Button, Canvas, DataList, Details, Dialog, Fieldset, Input, Label, Legend, Meter, NoScript, Output, Progress, Script, Select, Slot, Summary, Template, Textarea
 */

import * as ButtonStories from './../../inline/button/button.stories.js';
import * as FieldsetStories from './../../block/fieldset/fieldset.stories.js';

export default {
  title: "HTML5/Content Model/Form - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The form element represents a section of a document containing interactive controls for submitting information to a web server.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Form with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('form');
    parent.className = 'example';

    const child0 = ButtonStories.default.render(ButtonStories.Default.args);
    parent.appendChild(child0);
    const child1 = ButtonStories.default.render(ButtonStories.Default.args);
    parent.appendChild(child1);
    const child2 = FieldsetStories.default.render(FieldsetStories.Default.args);
    parent.appendChild(child2);
    const child3 = FieldsetStories.default.render(FieldsetStories.Default.args);
    parent.appendChild(child3);

    return parent;
  },
};
