/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Link
 * @description 
 */

export interface LinkProps {
  /**
   * 
   */
  crossorigin?: 'anonymous' | 'use-credentials' | null | undefined;
  /**
   * Represents the text direction of the element
   */
  dir?: 'ltr' | 'rtl' | 'auto' | null | undefined;
  /**
   * Indicates whether the element is hidden
   */
  hidden?: boolean | null | undefined;
  /**
   * Specifies the URL of the linked resource. Special protocols such as mailto: or tel: can be used.
   */
  href?: string | null | undefined;
  /**
   * Specifies the language of the linked resource.
   */
  hreflang?: string | null | undefined;
  /**
   * Specifies the integrity value of a resource.
   */
  integrity?: string | null | undefined;
  /**
   * Specifies the primary language for the element's content
   */
  lang?: string | null | undefined;
  /**
   * Specifies the media type for which the linked resource or style sheet is intended.
   */
  media?: string | null | undefined;
  /**
   * Specifies the referrer policy for fetches initiated by the element.
   */
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | null | undefined;
  /**
   * Specifies the relationship between the current document and the linked document.
   */
  rel?: 'alternate' | 'author' | 'bookmark' | 'canonical' | 'help' | 'icon' | 'license' | 'manifest' | 'next' | 'nofollow' | 'noreferrer' | 'prefetch' | 'prev' | 'search' | 'stylesheet' | 'tag' | null | undefined;
  /**
   * Specifies the sizes of the images or icons for different display/window sizes.
   */
  sizes?: string | null | undefined;
  /**
   * Represents the CSS inline style of the element
   */
  style?: string | null | undefined;
  /**
   * Represents a title or tooltip for the element
   */
  title?: string | null | undefined;
  /**
   * Specifies the media type of the linked resource.
   */
  type?: string | null | undefined;
}

/**
 * Link - 
 */
export class Link {
  private element: HTMLElement;

  constructor(props: LinkProps = {}) {
    this.element = document.createElement('link');
    this.applyProps(props);
  }

  private applyProps(props: LinkProps): void {
    if (props.crossorigin !== undefined) {
      this.setCrossorigin(props.crossorigin);
    }
    if (props.dir !== undefined) {
      this.setDir(props.dir);
    }
    if (props.hidden !== undefined) {
      this.element.setAttribute('hidden', String(props.hidden));
    }
    if (props.href !== undefined) {
      this.element.setAttribute('href', String(props.href));
    }
    if (props.hreflang !== undefined) {
      this.element.setAttribute('hreflang', String(props.hreflang));
    }
    if (props.integrity !== undefined) {
      this.element.setAttribute('integrity', String(props.integrity));
    }
    if (props.lang !== undefined) {
      this.element.setAttribute('lang', String(props.lang));
    }
    if (props.media !== undefined) {
      this.element.setAttribute('media', String(props.media));
    }
    if (props.referrerpolicy !== undefined) {
      this.setReferrerpolicy(props.referrerpolicy);
    }
    if (props.rel !== undefined) {
      this.setRel(props.rel);
    }
    if (props.sizes !== undefined) {
      this.element.setAttribute('sizes', String(props.sizes));
    }
    if (props.style !== undefined) {
      this.element.setAttribute('style', String(props.style));
    }
    if (props.title !== undefined) {
      this.element.setAttribute('title', String(props.title));
    }
    if (props.type !== undefined) {
      this.element.setAttribute('type', String(props.type));
    }
  }

  setCrossorigin(value: 'anonymous' | 'use-credentials' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('crossorigin');
    } else {
      this.element.setAttribute('crossorigin', String(value));
    }
    return this;
  }

  setDir(value: 'ltr' | 'rtl' | 'auto' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('dir');
    } else {
      this.element.setAttribute('dir', String(value));
    }
    return this;
  }

  setHidden(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('hidden', '');
    } else {
      this.element.removeAttribute('hidden');
    }
    return this;
  }

  setHref(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('href');
    } else {
      this.element.setAttribute('href', String(value));
    }
    return this;
  }

  setHreflang(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('hreflang');
    } else {
      this.element.setAttribute('hreflang', String(value));
    }
    return this;
  }

  setIntegrity(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('integrity');
    } else {
      this.element.setAttribute('integrity', String(value));
    }
    return this;
  }

  setLang(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('lang');
    } else {
      this.element.setAttribute('lang', String(value));
    }
    return this;
  }

  setMedia(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('media');
    } else {
      this.element.setAttribute('media', String(value));
    }
    return this;
  }

  setReferrerpolicy(value: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('referrerpolicy');
    } else {
      this.element.setAttribute('referrerpolicy', String(value));
    }
    return this;
  }

  setRel(value: 'alternate' | 'author' | 'bookmark' | 'canonical' | 'help' | 'icon' | 'license' | 'manifest' | 'next' | 'nofollow' | 'noreferrer' | 'prefetch' | 'prev' | 'search' | 'stylesheet' | 'tag' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('rel');
    } else {
      this.element.setAttribute('rel', String(value));
    }
    return this;
  }

  setSizes(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('sizes');
    } else {
      this.element.setAttribute('sizes', String(value));
    }
    return this;
  }

  setStyle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('style');
    } else {
      this.element.setAttribute('style', String(value));
    }
    return this;
  }

  setTitle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('title');
    } else {
      this.element.setAttribute('title', String(value));
    }
    return this;
  }

  setType(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('type');
    } else {
      this.element.setAttribute('type', String(value));
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
