/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Table - Composed Example
 * @description The table element represents tabular data — that is, information presented in a two-dimensional table comprised of rows and columns of cells containing data.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, Main, MarkedText, Paragraph, Section, Slot, Template
 * - Can contain: Caption, ColumnGroup, TableBody, TableFoot, TableHead, TableRow
 */

import * as CaptionStories from './../../block/caption/caption.stories.js';
import * as ColgroupStories from './../../block/colgroup/colgroup.stories.js';

export default {
  title: "HTML5/Content Model/Table - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The table element represents tabular data — that is, information presented in a two-dimensional table comprised of rows and columns of cells containing data.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Table with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('table');
    parent.className = 'example';

    const child0 = CaptionStories.default.render(CaptionStories.Default.args);
    parent.appendChild(child0);
    const child1 = ColgroupStories.default.render(ColgroupStories.Default.args);
    parent.appendChild(child1);
    const child2 = ColgroupStories.default.render(ColgroupStories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
