/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Meta
 * @description 
 */

export interface MetaProps {
  /**
   * Specifies the character encoding for the resource.
   */
  charset?: string | null | undefined;
  /**
   * Specifies the value associated with the http-equiv or name attribute.
   */
  content?: string | null | undefined;
  /**
   * Indicates whether the element is hidden
   */
  hidden?: boolean | null | undefined;
  /**
   * Provides an HTTP header for the information/value of the content attribute.
   */
  'http-equiv'?: 'content-language' | 'content-type' | 'default-style' | 'refresh' | null | undefined;
  /**
   * Specifies the primary language for the element's content
   */
  lang?: string | null | undefined;
  /**
   * Specifies the name associated with the element. The meaning may vary depending on the context.
   */
  name?: string | null | undefined;
  /**
   * Specifies the content type of the value attribute when the http-equiv attribute is used.
   */
  scheme?: string | null | undefined;
  /**
   * Represents a title or tooltip for the element
   */
  title?: string | null | undefined;
}

/**
 * Meta - 
 */
export class Meta {
  private element: HTMLElement;

  constructor(props: MetaProps = {}) {
    this.element = document.createElement('meta');
    this.applyProps(props);
  }

  private applyProps(props: MetaProps): void {
    if (props.charset !== undefined) {
      this.element.setAttribute('charset', String(props.charset));
    }
    if (props.content !== undefined) {
      this.element.setAttribute('content', String(props.content));
    }
    if (props.hidden !== undefined) {
      this.element.setAttribute('hidden', String(props.hidden));
    }
    if (props['http-equiv'] !== undefined) {
      this.setHttpEquiv(props['http-equiv']);
    }
    if (props.lang !== undefined) {
      this.element.setAttribute('lang', String(props.lang));
    }
    if (props.name !== undefined) {
      this.element.setAttribute('name', String(props.name));
    }
    if (props.scheme !== undefined) {
      this.element.setAttribute('scheme', String(props.scheme));
    }
    if (props.title !== undefined) {
      this.element.setAttribute('title', String(props.title));
    }
  }

  setCharset(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('charset');
    } else {
      this.element.setAttribute('charset', String(value));
    }
    return this;
  }

  setContent(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('content');
    } else {
      this.element.setAttribute('content', String(value));
    }
    return this;
  }

  setHidden(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('hidden', '');
    } else {
      this.element.removeAttribute('hidden');
    }
    return this;
  }

  setHttpEquiv(value: 'content-language' | 'content-type' | 'default-style' | 'refresh' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('http-equiv');
    } else {
      this.element.setAttribute('http-equiv', String(value));
    }
    return this;
  }

  setLang(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('lang');
    } else {
      this.element.setAttribute('lang', String(value));
    }
    return this;
  }

  setName(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('name');
    } else {
      this.element.setAttribute('name', String(value));
    }
    return this;
  }

  setScheme(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('scheme');
    } else {
      this.element.setAttribute('scheme', String(value));
    }
    return this;
  }

  setTitle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('title');
    } else {
      this.element.setAttribute('title', String(value));
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
