/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Ruby - Composed Template
 * @description The ruby element represents a ruby annotation. Ruby annotations are short runs of text presented alongside base text, primarily used for East Asian typography to indicate pronunciation or to provide a short annotation.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, Main, MarkedText, Paragraph, Section
 * - Can contain: RubyParenthesis, RubyText
 */

import React from 'react';
import { Ruby } from '../inline/ruby';
import { Rp } from '../inline/rp';
import { Rt } from '../inline/rt';

/**
 * Example usage of Ruby with valid content model
 */
export const RubyExample: React.FC = () => {
  return (
    <Ruby className="example">
      <Rp>Example content</Rp>
      <Rp>Example content</Rp>
      <Rt>annotation</Rt>
      <Rt>annotation</Rt>
    </Ruby>
  );
};

RubyExample.displayName = 'RubyExample';
