/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23
 * @component Hr
 * @description The hr element represents a thematic break between paragraph-level elements. It is typically a horizontal rule or line.
 */

export default {
  title: "HTML5/Block Elements/Hr",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Block Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The hr element represents a thematic break between paragraph-level elements. It is typically a horizontal rule or line.",
      },
    },
  },
  argTypes: {
    align: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "center", "justify", "left", "right"],
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    color: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    noshade: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    size: {
      type: {
        name: "number",
        required: false
      },
      defaultValue: 0,
      control: {
        type: "number"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    width: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: (args) => {
    let el = document.createElement("hr");

    // Map argument keys to attribute names, handle special cases
    const argMap = {
      classProp: 'class',
      style: 'style',
      tabindex: 'tabindex',
    };
    Object.entries(args).forEach(([key, value]) => {
      if (key === 'text' || value === undefined || value === "") return;
      if (key === 'data' && typeof value === 'object') {
        Object.keys(value).forEach(dataKey => {
          el.setAttribute(`data-${dataKey}`, value[dataKey]);
        });
        return;
      }
      const attr = argMap[key] || key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
      // Only set boolean attributes if true, omit if false
      if (typeof value === 'boolean') {
        if (value) {
          el.setAttribute(attr, "");
        }
        return;
      }
      el.setAttribute(attr, value);
    });
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    align: "",
    classProp: "Sample value",
    color: "Sample value",
    data: {},
    dir: "",
    hidden: false,
    id: "Sample value",
    lang: "Sample value",
    noshade: false,
    size: 0,
    style: "Sample value",
    title: "Sample value",
    width: "Sample value",
  },
};
