/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Figure - Composed Example
 * @description The figure element represents self-contained content, potentially with an optional caption, which is specified using the (optional) figcaption element.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, ListItem, Main, Paragraph, Section
 * - Can contain: FigureCaption, Image
 */

import * as FigcaptionStories from './../../block/figcaption/figcaption.stories.js';
import * as ImgStories from './../../inline/img/img.stories.js';

export default {
  title: "HTML5/Content Model/Figure - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The figure element represents self-contained content, potentially with an optional caption, which is specified using the (optional) figcaption element.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Figure with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('figure');
    parent.className = 'example';

    const child0 = FigcaptionStories.default.render(FigcaptionStories.Default.args);
    parent.appendChild(child0);
    const child1 = ImgStories.default.render(ImgStories.Default.args);
    parent.appendChild(child1);
    const child2 = ImgStories.default.render(ImgStories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
