/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Form
 * @description The form element represents a section of a document containing interactive controls for submitting information to a web server.
 */

import React from 'react';

export interface FormProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  acceptCharset?: string;
  accesskey?: string;
  action?: string;
  ariaAtomic?: 'false' | 'true';
  ariaDetails?: string;
  ariaInvalid?: 'false' | 'true' | 'grammar' | 'spelling';
  ariaKeyshortcuts?: string;
  ariaLabel?: string;
  ariaLive?: 'off' | 'polite' | 'assertive';
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  ariaRoledescription?: string;
  autocomplete?: 'off' | 'on';
  autocorrect?: 'off' | 'on';
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  enctype?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';
  hidden?: boolean;
  id?: string;
  lang?: string;
  method?: 'get' | 'post' | 'dialog';
  name?: string;
  novalidate?: boolean;
  slot?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  target?: '_self' | '_blank' | '_parent' | '_top';
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Form - The form element represents a section of a document containing interactive controls for submitting information to a web server.
 */
export const Form: React.FC<FormProps> = (props: FormProps) => {
  const {
    children,
    className,
    acceptCharset,
    accesskey,
    action,
    ariaAtomic,
    ariaDetails,
    ariaInvalid,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autocomplete,
    autocorrect,
    dataSet,
    dir,
    draggable,
    enctype,
    hidden,
    id,
    lang,
    method,
    name,
    novalidate,
    slot,
    style,
    tabindex,
    target,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'draggable' || key === 'hidden' || key === 'novalidate')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'form',
    elementProps,
    children
  );
};

Form.displayName = 'Form';
