/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Map - Composed Example
 * @description The map element, in conjunction with an img element and any area element descendants, defines an image map. The element represents a related collection of map areas.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, Main, MarkedText, Paragraph, Section
 * - Can contain: Area
 */

import * as AreaStories from './../../void/area/area.stories.js';

export default {
  title: "HTML5/Content Model/Map - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The map element, in conjunction with an img element and any area element descendants, defines an image map. The element represents a related collection of map areas.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Map with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('map');
    parent.className = 'example';

    const child0 = AreaStories.default.render(AreaStories.Default.args);
    parent.appendChild(child0);
    const child1 = AreaStories.default.render(AreaStories.Default.args);
    parent.appendChild(child1);

    return parent;
  },
};
