/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Picture - Composed Example
 * @description The picture element contains zero or more source elements and one img element to offer alternative versions of an image for different display/device scenarios.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, Main, MarkedText, Section
 * - Can contain: Image, Source
 */

import * as ImgStories from './../../inline/img/img.stories.js';
import * as SourceStories from './../../void/source/source.stories.js';

export default {
  title: "HTML5/Content Model/Picture - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The picture element contains zero or more source elements and one img element to offer alternative versions of an image for different display/device scenarios.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Picture with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('picture');
    parent.className = 'example';

    const child0 = ImgStories.default.render(ImgStories.Default.args);
    parent.appendChild(child0);
    const child1 = ImgStories.default.render(ImgStories.Default.args);
    parent.appendChild(child1);
    const child2 = SourceStories.default.render(SourceStories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
