/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Iframe
 * @description The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.
 */

import React from 'react';

export interface IframeProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  allowfullscreen?: boolean;
  ariaAtomic?: 'false' | 'true';
  ariaBusy?: 'true' | 'false';
  ariaControls?: string;
  ariaDescribedby?: string;
  ariaDetails?: string;
  ariaHidden?: 'false' | 'true';
  ariaKeyshortcuts?: string;
  ariaLabel?: string;
  ariaLabelledby?: string;
  ariaLive?: 'off' | 'polite' | 'assertive';
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  ariaRoledescription?: string;
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  height?: string;
  hidden?: boolean;
  id?: string;
  lang?: string;
  name?: string;
  popover?: 'auto' | 'hint' | 'manual';
  referrerpolicy?: 'no-referrer' | 'no-referrer-when-downgrade' | 'origin' | 'origin-when-cross-origin' | 'same-origin' | 'strict-origin' | 'strict-origin-when-cross-origin' | 'unsafe-url';
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  sandbox?: string;
  seamless?: boolean;
  slot?: string;
  src?: string;
  srcdoc?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  width?: string;
}

/**
 * Iframe - The iframe element represents a nested browsing context, effectively embedding another HTML page into the current page.
 */
export const Iframe: React.FC<IframeProps> = (props: IframeProps) => {
  const {
    children,
    className,
    allowfullscreen,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabel,
    ariaLabelledby,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    dataSet,
    dir,
    height,
    hidden,
    id,
    lang,
    name,
    popover,
    referrerpolicy,
    role,
    sandbox,
    seamless,
    slot,
    src,
    srcdoc,
    style,
    tabindex,
    title,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'allowfullscreen' || key === 'hidden' || key === 'seamless')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'iframe',
    elementProps,
    children
  );
};

Iframe.displayName = 'Iframe';
