/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Body - Composed Template
 * @description The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.
 *
 * CONTENT MODEL:
 * - Can be a child of: HTML
 * - Can contain: Anchor, Abbreviation, Address, Area, Article, Aside, Audio, Bold, BidirectionalIsolation, BidirectionalOverride, Blockquote, BreakElement, Button, Canvas, Citation, Code, Data, DataList, DeletedText, Details, Definition, Dialog, Division, DefinitionList, Emphasis, Embed, Fieldset, Figure, Footer, Form, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6, Header, HorizontalRule, Italic, InlineFrame, Image, Input, InsertedText, KeyboardInput, Label, Main, Map, MarkedText, Meter, Navigation, NoScript, ObjectElement, OrderedList, Output, Paragraph, Picture, PreformattedText, Progress, Quotation, Ruby, Strikethrough, SampleOutput, Script, Section, Select, Small, Span, Strong, Subscript, Superscript, Table, Template, Textarea, Time, Underline, UnorderedList, Variable, Video, WordBreakOpportunity
 * - UNIQUE: Only one allowed per document
 * - UNIQUE PER PARENT: Only one allowed per parent element
 */

import React from 'react';
import { Body } from '../block/body';
import { A } from '../inline/a';
import { Abbr } from '../inline/abbr';
import { Address } from '../inline/address';
import { Area } from '../void/area';
import { Article } from '../block/article';
import { Aside } from '../block/aside';
import { Audio } from '../block/audio';
import { B } from '../inline/b';
import { Bdi } from '../inline/bdi';
import { Bdo } from '../inline/bdo';
import { Blockquote } from '../block/blockquote';
import { P } from '../block/p';
import { Br } from '../void/br';
import { Button } from '../inline/button';
import { Canvas } from '../block/canvas';
import { Cite } from '../inline/cite';
import { Code } from '../inline/code';
import { Data } from '../inline/data';
import { Datalist } from '../block/datalist';
import { Option } from '../block/option';
import { Del } from '../block/del';
import { Details } from '../block/details';
import { Dfn } from '../inline/dfn';
import { Dialog } from '../block/dialog';
import { Div } from '../block/div';
import { Dl } from '../block/dl';
import { Dd } from '../block/dd';
import { Dt } from '../block/dt';
import { Em } from '../inline/em';
import { Embed } from '../block/embed';
import { Fieldset } from '../block/fieldset';
import { Figure } from '../block/figure';
import { Figcaption } from '../block/figcaption';
import { Img } from '../inline/img';
import { Footer } from '../block/footer';
import { Form } from '../block/form';
import { H1 } from '../block/h1';
import { H2 } from '../block/h2';
import { H3 } from '../block/h3';
import { H4 } from '../block/h4';
import { H5 } from '../block/h5';
import { H6 } from '../block/h6';
import { Header } from '../block/header';
import { Hr } from '../block/hr';
import { I } from '../inline/i';
import { Iframe } from '../block/iframe';
import { Input } from '../inline/input';
import { Ins } from '../block/ins';
import { Kbd } from '../inline/kbd';
import { Label } from '../inline/label';
import { Main } from '../block/main';
import { Map } from '../block/map';
import { Mark } from '../inline/mark';
import { Meter } from '../inline/meter';
import { Nav } from '../block/nav';
import { Q } from '../inline/q';
import { S } from '../inline/s';
import { Small } from '../inline/small';
import { Strong } from '../inline/strong';
import { Noscript } from '../block/noscript';
import { Object } from '../block/object';
import { Ol } from '../block/ol';
import { Li } from '../block/li';
import { Output } from '../inline/output';
import { Picture } from '../block/picture';
import { Source } from '../void/source';
import { Pre } from '../block/pre';
import { Progress } from '../inline/progress';
import { Ruby } from '../inline/ruby';
import { Rp } from '../inline/rp';
import { Rt } from '../inline/rt';
import { Samp } from '../inline/samp';
import { Script } from '../void/script';
import { Section } from '../block/section';
import { Select } from '../inline/select';
import { Optgroup } from '../block/optgroup';
import { Span } from '../inline/span';
import { Sub } from '../inline/sub';
import { Sup } from '../inline/sup';
import { Table } from '../block/table';
import { Caption } from '../block/caption';
import { Colgroup } from '../block/colgroup';
import { Col } from '../void/col';
import { Tbody } from '../block/tbody';
import { Tr } from '../block/tr';
import { Tfoot } from '../block/tfoot';
import { Thead } from '../block/thead';
import { Template } from '../block/template';
import { Textarea } from '../inline/textarea';
import { Time } from '../inline/time';
import { U } from '../inline/u';
import { Ul } from '../block/ul';
import { Var } from '../inline/var';
import { Video } from '../block/video';
import { Wbr } from '../void/wbr';

/**
 * Example usage of Body with valid content model
 */
export const BodyExample: React.FC = () => {
  return (
    <Body className="example">
      <A>Example content</A>
      <A>Example content</A>
      <Abbr>Example content</Abbr>
      <Abbr>Example content</Abbr>
      <Address>Example content</Address>
      <Area shape="rect" coords="0,0,100,100" href="#link3" alt="Area 3" />
      <Area shape="rect" coords="0,0,100,100" href="#link4" alt="Area 4" />
    </Body>
  );
};

BodyExample.displayName = 'BodyExample';
