/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component TrExample
 * @description  - Composed Example
 */

import { Tr } from './tr';

/**
 * TrExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Table, TableHead, TableBody, TableFoot
 * - Can contain: TableData, TableHeader
 */
export class TrExample {
  static create(): HTMLElement {
    const element = new Tr();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
