/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Output
 * @description 
 */

export interface OutputProps {
  /**
   * Child content or elements
   */
  children?: string | HTMLElement | (string | HTMLElement)[];
  /**
   * specifies a shortcut key (or keys) to activate or focus an element
   */
  accesskey?: string | null | undefined;
  /**
   * Indicates whether assistive technologies should present the entire region as a whole when changes occur.
   */
  'aria-atomic'?: 'false' | 'true' | boolean | null | undefined;
  /**
   * References an element that provides additional details about the current element.
   */
  'aria-details'?: string | null | undefined;
  /**
   * Defines keyboard shortcuts available for the element.
   */
  'aria-keyshortcuts'?: string | null | undefined;
  /**
   * Defines how updates to the element should be announced to screen readers.
   */
  'aria-live'?: 'off' | 'polite' | 'assertive' | null | undefined;
  /**
   * Indicates what content changes should be announced in a live region.
   */
  'aria-relevant'?: 'additions' | 'removals' | 'text' | 'all' | 'additions text' | null | undefined;
  /**
   * Provides a human-readable custom role description for assistive technologies.
   */
  'aria-roledescription'?: string | null | undefined;
  /**
   * Represents the autocapitalize behavior of the element
   */
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters' | null | undefined;
  /**
   * Specifies controls whether autocorrection of editable text is enabled for spelling and/or punctuation errors. Default is on.
   */
  autocorrect?: 'off' | 'on' | null | undefined;
  /**
   * Indicates whether the element is hidden
   */
  autofocus?: boolean | null | undefined;
  /**
   * Indicates whether the element can be edited in place
   */
  contenteditable?: 'true' | 'false' | 'inherit' | boolean | null | undefined;
  /**
   * Represents the text direction of the element
   */
  dir?: 'ltr' | 'rtl' | 'auto' | null | undefined;
  /**
   * Indicates whether the element is draggable
   */
  draggable?: boolean | null | undefined;
  /**
   * Refers to the <datalist> element that contains the options for an input element.
   */
  for?: string | null | undefined;
  /**
   * Indicates whether the element is hidden
   */
  hidden?: boolean | null | undefined;
  /**
   * used to specify the data entry mode for an input. It helps guide on-screen keyboards (especially on mobile devices) to show the appropriate layout for the expected input type
   */
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search' | null | undefined;
  /**
   * Specifies the primary language for the element's content
   */
  lang?: string | null | undefined;
  /**
   * Represents a slot in a shadow DOM
   */
  slot?: string | null | undefined;
  /**
   * Represents the spellchecking behavior of the element
   */
  spellcheck?: 'true' | 'false' | boolean | null | undefined;
  /**
   * Represents the CSS inline style of the element
   */
  style?: string | null | undefined;
  /**
   * Represents a tab order of the element
   */
  tabindex?: number | null | undefined;
  /**
   * Represents a title or tooltip for the element
   */
  title?: string | null | undefined;
  /**
   * used to tell user agents whether the content should be translated.
   */
  translate?: 'yes' | 'no' | null | undefined;
}

/**
 * Output - 
 */
export class Output {
  private element: HTMLElement;

  constructor(props: OutputProps = {}) {
    this.element = document.createElement('output');
    this.applyProps(props);
  }

  private applyProps(props: OutputProps): void {
    if (props.children !== undefined) {
      this.setChildren(props.children);
    }
    if (props.accesskey !== undefined) {
      this.element.setAttribute('accesskey', String(props.accesskey));
    }
    if (props['aria-atomic'] !== undefined) {
      this.setAriaAtomic(props['aria-atomic']);
    }
    if (props['aria-details'] !== undefined) {
      this.element.setAttribute('aria-details', String(props['aria-details']));
    }
    if (props['aria-keyshortcuts'] !== undefined) {
      this.element.setAttribute('aria-keyshortcuts', String(props['aria-keyshortcuts']));
    }
    if (props['aria-live'] !== undefined) {
      this.setAriaLive(props['aria-live']);
    }
    if (props['aria-relevant'] !== undefined) {
      this.setAriaRelevant(props['aria-relevant']);
    }
    if (props['aria-roledescription'] !== undefined) {
      this.element.setAttribute('aria-roledescription', String(props['aria-roledescription']));
    }
    if (props.autocapitalize !== undefined) {
      this.setAutocapitalize(props.autocapitalize);
    }
    if (props.autocorrect !== undefined) {
      this.setAutocorrect(props.autocorrect);
    }
    if (props.autofocus !== undefined) {
      this.element.setAttribute('autofocus', String(props.autofocus));
    }
    if (props.contenteditable !== undefined) {
      this.setContenteditable(props.contenteditable);
    }
    if (props.dir !== undefined) {
      this.setDir(props.dir);
    }
    if (props.draggable !== undefined) {
      this.element.setAttribute('draggable', String(props.draggable));
    }
    if (props.for !== undefined) {
      this.element.setAttribute('for', String(props.for));
    }
    if (props.hidden !== undefined) {
      this.element.setAttribute('hidden', String(props.hidden));
    }
    if (props.inputmode !== undefined) {
      this.setInputmode(props.inputmode);
    }
    if (props.lang !== undefined) {
      this.element.setAttribute('lang', String(props.lang));
    }
    if (props.slot !== undefined) {
      this.element.setAttribute('slot', String(props.slot));
    }
    if (props.spellcheck !== undefined) {
      this.setSpellcheck(props.spellcheck);
    }
    if (props.style !== undefined) {
      this.element.setAttribute('style', String(props.style));
    }
    if (props.tabindex !== undefined) {
      this.element.setAttribute('tabindex', String(props.tabindex));
    }
    if (props.title !== undefined) {
      this.element.setAttribute('title', String(props.title));
    }
    if (props.translate !== undefined) {
      this.setTranslate(props.translate);
    }
  }

  setAccesskey(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('accesskey');
    } else {
      this.element.setAttribute('accesskey', String(value));
    }
    return this;
  }

  setAriaAtomic(value: 'false' | 'true' | boolean | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('aria-atomic');
    } else {
      this.element.setAttribute('aria-atomic', String(value));
    }
    return this;
  }

  setAriaDetails(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('aria-details');
    } else {
      this.element.setAttribute('aria-details', String(value));
    }
    return this;
  }

  setAriaKeyshortcuts(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('aria-keyshortcuts');
    } else {
      this.element.setAttribute('aria-keyshortcuts', String(value));
    }
    return this;
  }

  setAriaLive(value: 'off' | 'polite' | 'assertive' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('aria-live');
    } else {
      this.element.setAttribute('aria-live', String(value));
    }
    return this;
  }

  setAriaRelevant(value: 'additions' | 'removals' | 'text' | 'all' | 'additions text' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('aria-relevant');
    } else {
      this.element.setAttribute('aria-relevant', String(value));
    }
    return this;
  }

  setAriaRoledescription(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('aria-roledescription');
    } else {
      this.element.setAttribute('aria-roledescription', String(value));
    }
    return this;
  }

  setAutocapitalize(value: 'none' | 'sentences' | 'words' | 'characters' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('autocapitalize');
    } else {
      this.element.setAttribute('autocapitalize', String(value));
    }
    return this;
  }

  setAutocorrect(value: 'off' | 'on' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('autocorrect');
    } else {
      this.element.setAttribute('autocorrect', String(value));
    }
    return this;
  }

  setAutofocus(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('autofocus', '');
    } else {
      this.element.removeAttribute('autofocus');
    }
    return this;
  }

  setContenteditable(value: 'true' | 'false' | 'inherit' | boolean | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('contenteditable');
    } else {
      this.element.setAttribute('contenteditable', String(value));
    }
    return this;
  }

  setDir(value: 'ltr' | 'rtl' | 'auto' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('dir');
    } else {
      this.element.setAttribute('dir', String(value));
    }
    return this;
  }

  setDraggable(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('draggable', '');
    } else {
      this.element.removeAttribute('draggable');
    }
    return this;
  }

  setFor(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('for');
    } else {
      this.element.setAttribute('for', String(value));
    }
    return this;
  }

  setHidden(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('hidden', '');
    } else {
      this.element.removeAttribute('hidden');
    }
    return this;
  }

  setInputmode(value: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('inputmode');
    } else {
      this.element.setAttribute('inputmode', String(value));
    }
    return this;
  }

  setLang(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('lang');
    } else {
      this.element.setAttribute('lang', String(value));
    }
    return this;
  }

  setSlot(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('slot');
    } else {
      this.element.setAttribute('slot', String(value));
    }
    return this;
  }

  setSpellcheck(value: 'true' | 'false' | boolean | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('spellcheck');
    } else {
      this.element.setAttribute('spellcheck', String(value));
    }
    return this;
  }

  setStyle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('style');
    } else {
      this.element.setAttribute('style', String(value));
    }
    return this;
  }

  setTabindex(value: number | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('tabindex');
    } else {
      this.element.setAttribute('tabindex', String(value));
    }
    return this;
  }

  setTitle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('title');
    } else {
      this.element.setAttribute('title', String(value));
    }
    return this;
  }

  setTranslate(value: 'yes' | 'no' | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('translate');
    } else {
      this.element.setAttribute('translate', String(value));
    }
    return this;
  }

  setChildren(children: string | HTMLElement | (string | HTMLElement)[]): this {
    // Clear existing children
    while (this.element.firstChild) {
      this.element.removeChild(this.element.firstChild);
    }
    
    if (typeof children === 'string') {
      this.element.textContent = children;
    } else if (Array.isArray(children)) {
      children.forEach(child => {
        if (typeof child === 'string') {
          this.element.appendChild(document.createTextNode(child));
        } else {
          this.element.appendChild(child);
        }
      });
    } else {
      this.element.appendChild(children);
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
