/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Head - Composed Template
 * @description The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.
 *
 * CONTENT MODEL:
 * - Can be a child of: HTML
 * - Can contain: Base, Link, Meta, NoScript, Script, Style, Title
 * - UNIQUE: Only one allowed per document
 * - UNIQUE PER PARENT: Only one allowed per parent element
 */

import React from 'react';
import { Head } from '../void/head';
import { Base } from '../void/base';
import { Link } from '../void/link';
import { Meta } from '../void/meta';
import { Noscript } from '../block/noscript';
import { Script } from '../void/script';
import { Style } from '../void/style';
import { Title } from '../void/title';

/**
 * Example usage of Head with valid content model
 */
export const HeadExample: React.FC = () => {
  return (
    <Head className="example">
      <Title>Page Title</Title>
      <Base />
      <Link />
      <Link />
      <Meta />
      <Meta />
      <Script>Example content</Script>
      <Script>Example content</Script>
      <Style>Example content</Style>
      <Style>Example content</Style>
    </Head>
  );
};

HeadExample.displayName = 'HeadExample';
