/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Figure - Composed Template
 * @description The figure element represents self-contained content, potentially with an optional caption, which is specified using the (optional) figcaption element.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, ListItem, Main, Paragraph, Section
 * - Can contain: FigureCaption, Image
 */

import React from 'react';
import { Figure } from '../block/figure';
import { Figcaption } from '../block/figcaption';
import { Img } from '../inline/img';

/**
 * Example usage of Figure with valid content model
 */
export const FigureExample: React.FC = () => {
  return (
    <Figure className="example">
      <Figcaption>Figure caption</Figcaption>
      <Img src="image.jpg" alt="Description" />
      <Img src="image.jpg" alt="Description" />
    </Figure>
  );
};

FigureExample.displayName = 'FigureExample';
