/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23
 * @component Style
 * @description The style element is used to embed CSS styles directly into an HTML document.
 */

export default {
  title: "HTML5/Void Elements/Style",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The style element is used to embed CSS styles directly into an HTML document.",
      },
    },
  },
  argTypes: {
    text: {
      type: {
        name: "string",
        required: true
      },
      description: "The text or HTML to display in the element",
      defaultValue: "Sample text",
      control: {
        type: "text"
      },
    },
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    media: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    nonce: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "text/css"],
    },
  },
  render: (args) => {
    let el = document.createElement("style");
    el.innerHTML = args.text;

    // Map argument keys to attribute names, handle special cases
    const argMap = {
      classProp: 'class',
      style: 'style',
      tabindex: 'tabindex',
    };
    Object.entries(args).forEach(([key, value]) => {
      if (key === 'text' || value === undefined || value === "") return;
      if (key === 'data' && typeof value === 'object') {
        Object.keys(value).forEach(dataKey => {
          el.setAttribute(`data-${dataKey}`, value[dataKey]);
        });
        return;
      }
      const attr = argMap[key] || key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
      // Only set boolean attributes if true, omit if false
      if (typeof value === 'boolean') {
        if (value) {
          el.setAttribute(attr, "");
        }
        return;
      }
      el.setAttribute(attr, value);
    });
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    text: "Sample text",
    classProp: "Sample value",
    data: {},
    dir: "",
    id: "Sample value",
    lang: "Sample value",
    media: "Sample value",
    nonce: "Sample value",
    title: "Sample value",
    type: "",
  },
};
