/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Body
 * @description The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.
 */

import React from 'react';

export interface BodyProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  lang?: string;
  onafterprint?: string;
  onbeforeprint?: string;
  onbeforeunload?: string;
  onhashchange?: string;
  onlanguagechange?: string;
  onmessage?: string;
  onmessageerror?: string;
  onoffline?: string;
  ononline?: string;
  onpagehide?: string;
  onpageshow?: string;
  onpopstate?: string;
  onrejectionhandled?: string;
  onstorage?: string;
  onunhandledrejection?: string;
  onunload?: string;
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Body - The body element represents the content of an HTML document. All the contents such as text, images, headings, links, tables, etc. are placed between the body tags.
 */
export const Body: React.FC<BodyProps> = (props: BodyProps) => {
  const {
    children,
    className,
    accesskey,
    dataSet,
    dir,
    draggable,
    hidden,
    id,
    lang,
    onafterprint,
    onbeforeprint,
    onbeforeunload,
    onhashchange,
    onlanguagechange,
    onmessage,
    onmessageerror,
    onoffline,
    ononline,
    onpagehide,
    onpageshow,
    onpopstate,
    onrejectionhandled,
    onstorage,
    onunhandledrejection,
    onunload,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'draggable' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'body',
    elementProps,
    children
  );
};

Body.displayName = 'Body';
