/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Col
 * @description 
 */

export interface ColProps {
  /**
   * Specifies the number of columns the <col> element should span in a table.
   */
  span?: number | null | undefined;
  /**
   * Represents the CSS inline style of the element
   */
  style?: string | null | undefined;
  /**
   * Specifies the width of the element. The meaning may vary depending on the element type. Accepts integers, pixels (px), and percentages (%).
   */
  width?: string | null | undefined;
}

/**
 * Col - 
 */
export class Col {
  private element: HTMLElement;

  constructor(props: ColProps = {}) {
    this.element = document.createElement('col');
    this.applyProps(props);
  }

  private applyProps(props: ColProps): void {
    if (props.span !== undefined) {
      this.element.setAttribute('span', String(props.span));
    }
    if (props.style !== undefined) {
      this.element.setAttribute('style', String(props.style));
    }
    if (props.width !== undefined) {
      this.element.setAttribute('width', String(props.width));
    }
  }

  setSpan(value: number | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('span');
    } else {
      this.element.setAttribute('span', String(value));
    }
    return this;
  }

  setStyle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('style');
    } else {
      this.element.setAttribute('style', String(value));
    }
    return this;
  }

  setWidth(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('width');
    } else {
      this.element.setAttribute('width', String(value));
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
