/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component SvgExample
 * @description  - Composed Example
 */

import { Svg } from './svg';

/**
 * SvgExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: ScalableVectorGraphics
 * - Can contain: Anchor, Script, Style, ScalableVectorGraphics, Title
 */
export class SvgExample {
  static create(): HTMLElement {
    const element = new Svg();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
