/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Col
 * @description The col element represents a column in a table.
 */

import React from 'react';

export interface ColProps {
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  id?: string;
  span?: number;
  style?: React.CSSProperties;
  width?: string;
}

/**
 * Col - The col element represents a column in a table.
 */
export const Col: React.FC<ColProps> = (props: ColProps) => {
  const {
    className,
    dataSet,
    id,
    span,
    style,
    width
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    elementProps[attrName] = value;
  });

  return React.createElement(
    'col',
    elementProps
  );
};

Col.displayName = 'Col';
