/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Span
 * @description The span element doesn't mean anything on its own, but can be useful when used together with the global attributes, e.g. class, lang, or dir. It represents its children.
 */

import React from 'react';

export interface SpanProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  accesskey?: string;
  ariaAtomic?: 'false' | 'true';
  ariaBusy?: 'true' | 'false';
  ariaControls?: string;
  ariaDescribedby?: string;
  ariaDetails?: string;
  ariaHidden?: 'false' | 'true';
  ariaKeyshortcuts?: string;
  ariaLabelledby?: string;
  ariaLive?: 'off' | 'polite' | 'assertive';
  ariaRelevant?: 'additions' | 'removals' | 'text' | 'all' | 'additions text';
  ariaRoledescription?: string;
  autocapitalize?: 'none' | 'sentences' | 'words' | 'characters';
  autofocus?: boolean;
  contenteditable?: 'true' | 'false' | 'inherit';
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
  dir?: 'ltr' | 'rtl' | 'auto';
  draggable?: boolean;
  hidden?: boolean;
  id?: string;
  inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'email' | 'tel' | 'url' | 'search';
  lang?: string;
  popover?: 'auto' | 'hint' | 'manual';
  role?: 'alert' | 'application' | 'article' | 'banner' | 'button' | 'checkbox' | 'complementary' | 'contentinfo' | 'dialog' | 'form' | 'grid' | 'group' | 'heading' | 'img' | 'link' | 'list' | 'listbox' | 'listitem' | 'main' | 'menu' | 'menubar' | 'menuitem' | 'navigation' | 'none' | 'presentation' | 'radio' | 'region' | 'search' | 'status' | 'tab' | 'tablist' | 'tabpanel' | 'textbox' | 'toolbar' | 'tooltip';
  slot?: string;
  spellcheck?: 'true' | 'false';
  style?: React.CSSProperties;
  tabindex?: number;
  title?: string;
  translate?: 'yes' | 'no';
}

/**
 * Span - The span element doesn't mean anything on its own, but can be useful when used together with the global attributes, e.g. class, lang, or dir. It represents its children.
 */
export const Span: React.FC<SpanProps> = (props: SpanProps) => {
  const {
    children,
    className,
    accesskey,
    ariaAtomic,
    ariaBusy,
    ariaControls,
    ariaDescribedby,
    ariaDetails,
    ariaHidden,
    ariaKeyshortcuts,
    ariaLabelledby,
    ariaLive,
    ariaRelevant,
    ariaRoledescription,
    autocapitalize,
    autofocus,
    contenteditable,
    dataSet,
    dir,
    draggable,
    hidden,
    id,
    inputmode,
    lang,
    popover,
    role,
    slot,
    spellcheck,
    style,
    tabindex,
    title,
    translate
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    // Handle boolean props that need explicit conversion
    if (typeof value === 'boolean' && (key === 'autofocus' || key === 'draggable' || key === 'hidden')) {
      elementProps[attrName] = value ? true : false;
    } else {
      elementProps[attrName] = value;
    }
  });

  return React.createElement(
    'span',
    elementProps,
    children
  );
};

Span.displayName = 'Span';
