/**
 *
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23
 * @component Link
 * @description The link element defines a link between a document and an external resource. It is used to link to external stylesheets.
 */

export default {
  title: "HTML5/Void Elements/Link",
  tags: ["autodocs"],
  parameters: {
    actions: {
      handles: ['change'],
    },
    layout: "centered",
    componentSubtitle: "Void Element",
    docs: {
      inlineStories: true,
      source: true,
      description: {
        component: "The link element defines a link between a document and an external resource. It is used to link to external stylesheets.",
      },
    },
  },
  argTypes: {
    classProp: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    crossorigin: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "anonymous", "use-credentials"],
    },
    data: {
      type: {
        name: "object",
        required: false
      },
      description: "Custom data attributes (data-*). Provide an object with key-value pairs.",
      defaultValue: {},
      control: {
        type: "object"
      },
    },
    dir: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "ltr", "rtl", "auto"],
    },
    hidden: {
      type: {
        name: "boolean",
        required: false
      },
      defaultValue: true,
      control: {
        type: "boolean"
      },
    },
    href: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    hreflang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    id: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    integrity: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    lang: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    media: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    referrerpolicy: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "no-referrer", "no-referrer-when-downgrade", "origin", "origin-when-cross-origin", "same-origin", "strict-origin", "strict-origin-when-cross-origin", "unsafe-url"],
    },
    rel: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "",
      control: {
        type: "select"
      },
      options: ["", "alternate", "author", "bookmark", "canonical", "help", "icon", "license", "manifest", "next", "nofollow", "noreferrer", "prefetch", "prev", "search", "stylesheet", "tag"],
    },
    sizes: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    style: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    title: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
    type: {
      type: {
        name: "string",
        required: false
      },
      defaultValue: "Sample value",
      control: {
        type: "text"
      },
    },
  },
  render: (args) => {
    let el = document.createElement("link");

    // Map argument keys to attribute names, handle special cases
    const argMap = {
      classProp: 'class',
      style: 'style',
      tabindex: 'tabindex',
    };
    Object.entries(args).forEach(([key, value]) => {
      if (key === 'text' || value === undefined || value === "") return;
      if (key === 'data' && typeof value === 'object') {
        Object.keys(value).forEach(dataKey => {
          el.setAttribute(`data-${dataKey}`, value[dataKey]);
        });
        return;
      }
      const attr = argMap[key] || key.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
      // Only set boolean attributes if true, omit if false
      if (typeof value === 'boolean') {
        if (value) {
          el.setAttribute(attr, "");
        }
        return;
      }
      el.setAttribute(attr, value);
    });
    return el;
  },
  decorators: [],
};

export const Default = {
  parameters: {
    docs: {
      description: {
        story: 'Default story with all arguments set to default values'
      },
    },
  },
  args: {
    classProp: "Sample value",
    crossorigin: "",
    data: {},
    dir: "",
    hidden: false,
    href: "Sample value",
    hreflang: "Sample value",
    id: "Sample value",
    integrity: "Sample value",
    lang: "Sample value",
    media: "Sample value",
    referrerpolicy: "",
    rel: "",
    sizes: "Sample value",
    style: "Sample value",
    title: "Sample value",
    type: "Sample value",
  },
};
