/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Dl - Composed Example
 * @description The dl element represents an association list consisting of zero or more name-value groups (a description list). Each group must consist of one or more names (dt elements) followed by one or more values (dd elements). Within a single dl element, there should not be more than one dt element for each name.
 *
 * CONTENT MODEL:
 * - Can be a child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, ListItem, Main, Paragraph, Section, Slot, Template
 * - Can contain: DefinitionDescription, DefinitionTerm
 */

import * as DdStories from './../../block/dd/dd.stories.js';
import * as DtStories from './../../block/dt/dt.stories.js';

export default {
  title: "HTML5/Content Model/Dl - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The dl element represents an association list consisting of zero or more name-value groups (a description list). Each group must consist of one or more names (dt elements) followed by one or more values (dd elements). Within a single dl element, there should not be more than one dt element for each name.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Dl with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('dl');
    parent.className = 'example';

    const child0 = DdStories.default.render(DdStories.Default.args);
    parent.appendChild(child0);
    const child1 = DtStories.default.render(DtStories.Default.args);
    parent.appendChild(child1);

    return parent;
  },
};
