/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component DetailsExample
 * @description  - Composed Example
 */

import { Details } from './details';

/**
 * DetailsExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Aside, Body, DefinitionDescription, Dialog, Division, Footer, Form, Header, Main, MarkedText, Paragraph, Section, Slot, Template
 * - Can contain: Division, DefinitionList, Form, ListItem, OrderedList, Paragraph, PreformattedText, Summary, Table, UnorderedList
 */
export class DetailsExample {
  static create(): HTMLElement {
    const element = new Details();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
