/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Datalist - Composed Example
 * @description The datalist element contains a set of option elements that represent the permissible or recommended options available to users.
 *
 * CONTENT MODEL:
 * - Can be a child of: Body, Fieldset, Form
 * - Can contain: Option
 */

import * as OptionStories from './../../block/option/option.stories.js';

export default {
  title: "HTML5/Content Model/Datalist - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The datalist element contains a set of option elements that represent the permissible or recommended options available to users.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Datalist with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('datalist');
    parent.className = 'example';

    const child0 = OptionStories.default.render(OptionStories.Default.args);
    parent.appendChild(child0);
    const child1 = OptionStories.default.render(OptionStories.Default.args);
    parent.appendChild(child1);

    return parent;
  },
};
