/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component ColgroupExample
 * @description  - Composed Example
 */

import { Colgroup } from './colgroup';

/**
 * ColgroupExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Table
 * - Can contain: Column
 */
export class ColgroupExample {
  static create(): HTMLElement {
    const element = new Colgroup();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
