/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component FigureExample
 * @description  - Composed Example
 */

import { Figure } from './figure';

/**
 * FigureExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Article, Aside, Body, DefinitionDescription, Division, Footer, Header, ListItem, Main, Paragraph, Section
 * - Can contain: FigureCaption, Image
 */
export class FigureExample {
  static create(): HTMLElement {
    const element = new Figure();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
