/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Param
 * @description 
 */

export interface ParamProps {
  /**
   * Indicates whether the element is hidden
   */
  hidden?: boolean | null | undefined;
  /**
   * Specifies the name associated with the element. The meaning may vary depending on the context.
   */
  name?: string | null | undefined;
  /**
   * Represents the CSS inline style of the element
   */
  style?: string | null | undefined;
  /**
   * Specifies the value associated with the element. The meaning and usage may vary depending on the element type.
   */
  value?: string | null | undefined;
}

/**
 * Param - 
 */
export class Param {
  private element: HTMLElement;

  constructor(props: ParamProps = {}) {
    this.element = document.createElement('param');
    this.applyProps(props);
  }

  private applyProps(props: ParamProps): void {
    if (props.hidden !== undefined) {
      this.element.setAttribute('hidden', String(props.hidden));
    }
    if (props.name !== undefined) {
      this.element.setAttribute('name', String(props.name));
    }
    if (props.style !== undefined) {
      this.element.setAttribute('style', String(props.style));
    }
    if (props.value !== undefined) {
      this.element.setAttribute('value', String(props.value));
    }
  }

  setHidden(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('hidden', '');
    } else {
      this.element.removeAttribute('hidden');
    }
    return this;
  }

  setName(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('name');
    } else {
      this.element.setAttribute('name', String(value));
    }
    return this;
  }

  setStyle(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('style');
    } else {
      this.element.setAttribute('style', String(value));
    }
    return this;
  }

  setValue(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('value');
    } else {
      this.element.setAttribute('value', String(value));
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
