/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Head
 * @description The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.
 */

import React from 'react';

export interface HeadProps {
  /** The content to display in the element */
  children?: React.ReactNode;
  /** CSS class names */
  className?: string;
  /** Custom data attributes (data-*) */
  dataSet?: Record<string, string>;
}

/**
 * Head - The head element contains meta-information about the HTML document, including its title and links to its scripts and stylesheets.
 */
export const Head: React.FC<HeadProps> = (props: HeadProps) => {
  const {
    children,
    className,
    dataSet
  } = props;

  const elementProps: React.HTMLAttributes<HTMLElement> & Record<string, any> = {};

  // Handle data attributes specially
  if (dataSet) {
    Object.entries(dataSet).forEach(([key, value]: [string, string]) => {
      elementProps[`data-${key}`] = value;
    });
  }

  // Convert camelCase to kebab-case for attribute names
  const toKebabCase = (str: string): string => {
    return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  };

  // Props to exclude from automatic mapping
  const excludedProps = new Set(['children', 'data']);

  // Iterate over all props and map them to element attributes
  Object.entries(props).forEach(([key, value]: [string, any]) => {
    if (excludedProps.has(key) || value === undefined) {
      return;
    }

    // Convert camelCase aria/contenteditable/autocapitalize to kebab-case
    const attrName = key.startsWith('aria') || key === 'contenteditable' || key === 'autocapitalize' 
      ? toKebabCase(key)
      : key;

    elementProps[attrName] = value;
  });

  return React.createElement(
    'head',
    elementProps,
    children
  );
};

Head.displayName = 'Head';
