/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component Hgroup - Composed Example
 * @description The hgroup element represents a multi-level heading for a section of a document. It groups a set of h1–h6 elements.
 *
 * CONTENT MODEL:
 * - Can contain: Heading1, Heading2, Heading3, Heading4, Heading5, Heading6
 */

import * as H1Stories from './../../block/h1/h1.stories.js';
import * as H2Stories from './../../block/h2/h2.stories.js';

export default {
  title: "HTML5/Content Model/Hgroup - Composed",
  tags: ["autodocs"],
  parameters: {
    layout: "centered",
    componentSubtitle: "Composed Example with Valid Children",
    docs: {
      description: {
        component: "The hgroup element represents a multi-level heading for a section of a document. It groups a set of h1–h6 elements.",
      },
    },
  },
};

export const WithValidChildren = {
  parameters: {
    docs: {
      description: {
        story: 'Example showing Hgroup with its valid child elements based on HTML5 content model'
      },
    },
  },
  render: () => {
    const parent = document.createElement('hgroup');
    parent.className = 'example';

    const child0 = H1Stories.default.render(H1Stories.Default.args);
    parent.appendChild(child0);
    const child1 = H1Stories.default.render(H1Stories.Default.args);
    parent.appendChild(child1);
    const child2 = H2Stories.default.render(H2Stories.Default.args);
    parent.appendChild(child2);

    return parent;
  },
};
