/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:40
 * @component Source
 * @description 
 */

export interface SourceProps {
  /**
   * Indicates whether the element is hidden
   */
  hidden?: boolean | null | undefined;
  /**
   * Specifies the media type for which the linked resource or style sheet is intended.
   */
  media?: string | null | undefined;
  /**
   * Specifies the sizes of the images or icons for different display/window sizes.
   */
  sizes?: string | null | undefined;
  /**
   * Specifies the URL of the external resource to be embedded or referenced.
   */
  src?: string | null | undefined;
  /**
   * Specifies a list of possible image sources for the browser to use.
   */
  srcset?: string | null | undefined;
  /**
   * Specifies the media type of the linked resource.
   */
  type?: string | null | undefined;
}

/**
 * Source - 
 */
export class Source {
  private element: HTMLElement;

  constructor(props: SourceProps = {}) {
    this.element = document.createElement('source');
    this.applyProps(props);
  }

  private applyProps(props: SourceProps): void {
    if (props.hidden !== undefined) {
      this.element.setAttribute('hidden', String(props.hidden));
    }
    if (props.media !== undefined) {
      this.element.setAttribute('media', String(props.media));
    }
    if (props.sizes !== undefined) {
      this.element.setAttribute('sizes', String(props.sizes));
    }
    if (props.src !== undefined) {
      this.element.setAttribute('src', String(props.src));
    }
    if (props.srcset !== undefined) {
      this.element.setAttribute('srcset', String(props.srcset));
    }
    if (props.type !== undefined) {
      this.element.setAttribute('type', String(props.type));
    }
  }

  setHidden(value: boolean | null | undefined): this {
    if (value === true) {
      this.element.setAttribute('hidden', '');
    } else {
      this.element.removeAttribute('hidden');
    }
    return this;
  }

  setMedia(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('media');
    } else {
      this.element.setAttribute('media', String(value));
    }
    return this;
  }

  setSizes(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('sizes');
    } else {
      this.element.setAttribute('sizes', String(value));
    }
    return this;
  }

  setSrc(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('src');
    } else {
      this.element.setAttribute('src', String(value));
    }
    return this;
  }

  setSrcset(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('srcset');
    } else {
      this.element.setAttribute('srcset', String(value));
    }
    return this;
  }

  setType(value: string | null | undefined): this {
    if (value === null || value === undefined) {
      this.element.removeAttribute('type');
    } else {
      this.element.setAttribute('type', String(value));
    }
    return this;
  }

  getElement(): HTMLElement {
    return this.element;
  }
}
