/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component SelectExample
 * @description  - Composed Example
 */

import { Select } from './select';

/**
 * SelectExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Aside, Body, DefinitionDescription, Dialog, Division, Fieldset, Footer, Form, Header, Main, MarkedText, Paragraph, Section, Slot, Template
 * - Can contain: OptionGroup, Option
 */
export class SelectExample {
  static create(): HTMLElement {
    const element = new Select();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
