/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component TemplateExample
 * @description  - Composed Example
 */

import { Template } from './template';

/**
 * TemplateExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Body, Form, Menu
 * - Can contain: Division, DefinitionList, Form, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6, Anchor, Button, Input, Select, Textarea, Details, Summary, InlineFrame, ListItem, OrderedList, Paragraph, PreformattedText, Table, UnorderedList
 */
export class TemplateExample {
  static create(): HTMLElement {
    const element = new Template();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
