/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component UlExample
 * @description  - Composed Example
 */

import { Ul } from './ul';

/**
 * UlExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Article, Aside, Body, DefinitionDescription, Details, Dialog, Division, Footer, Header, ListItem, Main, Paragraph, Section, Slot, Template
 * - Can contain: ListItem
 */
export class UlExample {
  static create(): HTMLElement {
    const element = new Ul();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
