/**
 * THIS FILE IS AUTOGENERATED. DO NOT EDIT IT.
 *
 * @generated December 28, 2025 17:23:19
 * @component LiExample
 * @description  - Composed Example
 */

import { Li } from './li';

/**
 * LiExample - Demonstrates valid parent-child relationships
 *
 * CONTENT MODEL:
 * - Can be child of: Aside, DefinitionDescription, Details, Dialog, Division, Footer, Header, Main, Menu, OrderedList, Section, Slot, Template, UnorderedList
 * - Can contain: Anchor, Abbreviation, Citation, Code, Data, Definition, Division, DefinitionList, Emphasis, Figure, Italic, KeyboardInput, OrderedList, Paragraph, PreformattedText, Quotation, Strikethrough, SampleOutput, Small, Strong, Subscript, Superscript, Time, Underline, UnorderedList, Variable
 */
export class LiExample {
  static create(): HTMLElement {
    const element = new Li();
    
    // Add example content
    // This would include valid child elements based on content model
    
    return element.getElement();
  }
}
